version: '2'

services:
  web_sekolah:
    container_name: web_sekolah
    image: php:5.6.10-apache
    volumes:
      - ./app/web:/var/www/html

  ppdb:
    container_name: ppdb
    image: php:7.3.7-apache
    volumes:
      - ./app/web:/var/www/html

  proxy:
    container_name: proxy
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ./config/dev-nginx.conf:/etc/nginx/nginx.conf
    links:
      - "web_sekolah"
      - "ppdb"
